# Generated by Django 4.2.2 on 2023-07-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_orders_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='acc_Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='refu',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
