# Generated by Django 4.2.2 on 2023-07-21 01:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_orders_acc_name_orders_refu'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('ticketObjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
