# Generated by Django 4.2.2 on 2023-07-24 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_product_managers_remove_product_date_and_more'),
        ('Event', '0003_alter_tickets_order_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets_order',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Store.product'),
        ),
    ]
