# Generated by Django 4.2.2 on 2023-07-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_alter_tickets_order_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_booked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
