# Generated by Django 4.2.2 on 2023-08-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_rename_date_ticket_from_t_remove_ticket_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='from_d',
            field=models.DateField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='to_d',
            field=models.DateField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='from_t',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='to_t',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
