# Generated by Django 4.2.2 on 2023-06-30 17:12

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import music_nation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30)),
                ('uploaded_on', models.DateField(default=datetime.datetime(2023, 6, 30, 17, 12, 37, 621475, tzinfo=datetime.timezone.utc))),
                ('album_logo', models.FileField(upload_to=music_nation.models.user_directory_path)),
                ('album_genre', models.CharField(choices=[('Amapiano', 'Amapiano'), ('Rock', 'Rock')], default='Rock', max_length=30)),
                ('album_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=40)),
                ('Artist', models.CharField(blank=True, default='IK', max_length=40, null=True)),
                ('song_file', models.FileField(upload_to=music_nation.models.user_directory_path_song)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('song_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_nation.album')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('Artist', 'Artist'), ('Just a user', 'Just a user')], max_length=40)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('fb', models.URLField(blank=True, null=True)),
                ('tweeter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('background', models.CharField(blank=True, max_length=200, null=True)),
                ('fullBiography', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
