# Generated by Django 4.2.2 on 2023-07-02 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 23, 53, 14, 959156, tzinfo=datetime.timezone.utc)),
        ),
    ]
