# Generated by Django 4.2.2 on 2023-07-03 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0003_alter_album_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 0, 33, 12, 312948, tzinfo=datetime.timezone.utc)),
        ),
    ]
