# Generated by Django 4.2.2 on 2023-07-21 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0006_alter_album_album_genre_alter_album_uploaded_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2023, 7, 21, 1, 40, 53, 180732, tzinfo=datetime.timezone.utc)),
        ),
    ]
