# Generated by Django 4.2.2 on 2023-07-21 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0007_alter_album_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2023, 7, 21, 1, 43, 10, 353825, tzinfo=datetime.timezone.utc)),
        ),
    ]
