# Generated by Django 4.2.2 on 2023-07-24 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0012_alter_album_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 0, 44, 22, 806228, tzinfo=datetime.timezone.utc)),
        ),
    ]
