# Generated by Django 4.2.2 on 2023-08-18 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0018_alter_album_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcasts',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Arts', 'Arts'), ('Business', 'Business'), ('Comedy', 'Comedy'), ('Education', 'Education'), ('Fiction', 'Fiction'), ('Government', 'Government'), ('History', 'History'), ('Health & Fitness', 'Health & Fitness'), ('Kids & Family', 'Kids & Family'), ('Leisure', 'Leisure'), ('News', 'News'), ('Religion & Spirituality', 'Religion & Spirituality'), ('Science', 'Science'), ('Society & Culture', 'Society & Culture'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('True Crime', 'True Crime'), ('TV & Film', 'TV & Film')], default='Music', max_length=40),
        ),
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2023, 8, 18, 22, 35, 1, 268898, tzinfo=datetime.timezone.utc)),
        ),
    ]
